In [1]:
import numpy as np
a=np.ones((2,5), dtype=np.float32)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
b=np.zeros((3,3), dtype=np.float32)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
c=np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print(c.ndim, c.shape, c.dtype)
print(c)

2 (2, 3) float32
[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
d=np.arange(5,10)
print(d)

[5 6 7 8 9]


In [10]:
e=np.arange(1,10,2)
print(e)

[1 3 5 7 9]


In [16]:
f=np.linspace(2.0, 3.0, num=5, endpoint=False)
print(f)
g=np.linspace(2.0, 3.0)
print(g)

[2.  2.2 2.4 2.6 2.8]
[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]


In [18]:
x=np.ones((1,3))
print(x)
y=np.zeros((3,3))
print(y)
xy=np.concatenate([x,y], axis=0)
print(xy)

[[1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
k=np.ones((3,3))
print(k)
l=np.zeros_like(k)
print(l)
m=np.zeros((2,2))
n=np.ones_like(m)
print(n)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [22]:
o=np.random.rand(3,5)
print(o)
p=np.random.randint(5, 10, size=(2,2))
print(p)

[[0.40846349 0.53542725 0.77719739 0.08942036 0.88030873]
 [0.68354    0.27276849 0.16956044 0.5837809  0.59632613]
 [0.40773111 0.23812276 0.35734137 0.25496904 0.96997333]]
[[8 8]
 [7 6]]


In [24]:
q=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(q)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
q[0][3]

4

In [28]:
q[0:1,0:3]

array([[1, 2, 3]])

In [29]:
r=np.array([1,2,3,4,5,6,7,8,9])
s=np.array([1,4,7])
r[s]

array([2, 5, 8])

In [30]:
t=np.array([[1, -8, -2 ], [1, 9, -5]])
print(t)

[[ 1 -8 -2]
 [ 1  9 -5]]


In [32]:
t[t<0]
t[t>0]

array([1, 1, 9])