In [2]:
import numpy as np
my_array=np.arange(30, 70, dtype=int)
print(my_array)
print(my_array.shape)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
(40,)


In [11]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b=np.array([[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
c=np.concatenate((a,b),axis=0)
print(c.shape)
print(c)

(6, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
