In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a+2
c=a*2
print(b)
print(c)

[3 4 5 6 7]
[ 2  4  6  8 10]


In [8]:
d=np.array([1,2,3,4,5])
e=np.array([6,7,8,9,10])
f=np.add(d,e)
print(d+e)
print(d-e)
print(d*e)
x=np.array([2,6,7,8,9,5])
#y=x+f

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [12]:
g=np.array([[1,2],[3,4],[5,6]])
print(g)
print(g.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [13]:
h=np.array([10,20])
print(h)
print(h.shape)

[10 20]
(2,)


In [15]:
j=g+h
print(j)
j.shape


[[11 22]
 [13 24]
 [15 26]]


(3, 2)

In [17]:
k=np.reshape(x,(2,3), order='F')
print(k)
k.shape

[[2 7 9]
 [6 8 5]]


(2, 3)

In [22]:
l=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(l)


[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
print(l.flatten())
print(l.flatten(order='F'))


[ 1  2  3  3  4  5  6  7  8  9 10 11]
[ 1  6  3  9  2  7  4 10  3  8  5 11]


In [24]:
np.ravel(l)

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
k=np.transpose(g)
l=np.swapaxes(g,0,1)
print(k)
print(l)
print(g.shape)
print(k.shape)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]
(3, 2)
(2, 3)


In [32]:
help(np.swapaxes)

Help on function swapaxes in module numpy:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier NumPy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    array([[1],
           [2],
           [3]])
    
    >>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    >>> x
    array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
    
    >>> np.swapaxes(x,0,2)
    array([[[0, 4],
            [2, 6]],
           [[1, 5],
            [3, 7]]])



In [33]:
o=np.array([1,2,3,4,5,6,7])
p=np.insert(o,3,10)
print(p)

[ 1  2  3 10  4  5  6  7]


In [34]:
q=np.append(o, 8)
print(q)

[1 2 3 4 5 6 7 8]


In [35]:
r=np.delete(q,6)
print(r)

[1 2 3 4 5 6 8]


In [42]:
s=np.array([[1,2],[2,2]])
t=np.array([[2,3],[1,2]])
u=s*t
print(u)

[[2 6]
 [2 4]]


In [50]:
v=np.matrix("1 2;3,4")
print(v)

[[1 2]
 [3 4]]


In [51]:
w=np.linalg.inv(v)
print(w)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [52]:
nul=v*w
print(nul)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [54]:
z=np.linalg.matrix_power(w,-2)
print(z)

[[ 7. 10.]
 [15. 22.]]


In [56]:
eq1=np.array([[3,1],[1,2]])
eq2=np.array([9,8])
eq1_det=np.linalg.det(eq1)
print(eq1_det)
result=np.linalg.solve(eq1,eq2)
print(result)

5.000000000000001
[2. 3.]
